# Generated by Django 3.2.6 on 2021-10-08 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpost',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='get_posts', to='news.category', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='newpost',
            name='img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
