# Generated by Django 3.2.6 on 2021-10-09 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20211008_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpost',
            name='pub_date',
            field=models.DateTimeField(),
        ),
    ]
