# Generated by Django 3.2.6 on 2021-10-25 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_applications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applications',
            name='file',
        ),
        migrations.AddField(
            model_name='applications',
            name='file_exe',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='applications',
            name='file_py',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
