# Generated by Django 3.2.6 on 2021-10-25 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20211025_0836'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applications',
            old_name='file_exe',
            new_name='file',
        ),
        migrations.RemoveField(
            model_name='applications',
            name='file_py',
        ),
    ]
